version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "sonartest-krishna"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
        - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
        - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
        - echo Build started 
        - ng build
        - sonar-scanner
            -Dsonar.login=$SONAR_TOKEN
            -Dsonar.host.url=$SONAR_ENDPOINT
            -Dsonar.projectKey=$PROJECT
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
